services:
  mysql:
    container_name: mysql_container
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 4229  # root password set as 4229
      MYSQL_DATABASE: job_application  # database name as job_application
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3307:3306"  # Host port 3307 mapped to container port 3306
    networks:
      - mysql
    restart: unless-stopped

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306  # The MySQL container is still listening on port 3306 inside the container
      PMA_USER: root
      PMA_PASSWORD: 4229
    volumes:
      - phpmyadmin:/var/www/html
    ports:
      - "5050:80"
    networks:
      - mysql
    restart: unless-stopped

networks:
  mysql:
    driver: bridge

volumes:
  mysql:
  phpmyadmin:
